apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: node_starter_template
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node_starter_template
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
